### ISSUE TITLE
[Bug] UI Element lost in macOS

### ISSUE THREAD

**Issue by hiberabyss** [Giotino/stegsolve#1]
When use data extract, the UI lost some element.

![image](https://user-images.githubusercontent.com/2898670/67161240-2ba8d780-f38b-11e9-9763-027acc8467c2.png)

**Comment by Giotino** [comment]
Hi, it should be fixed in the new pre-release [https://github.com/Giotino/stegsolve/releases/tag/v.1.5](https://github.com/Giotino/stegsolve/releases/tag/v.1.5)
